packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - '@scarf/scarf'
  - core-js-pure
  - esbuild

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - bcrypt
  - prisma
